#!/bin/bash

INSTALLDIR="$1"
unset LD_LIBRARY_PATH # Use system libraries, this was set Tauri's AppImage builder
export WINEDEBUG=err+all,fixme-all

mkdir "$INSTALLDIR/temp"
if [ $? -ne 0 ] ; then
    echo "temp dir already exists"
    exit 1
fi

abort_and_cleanup () {
    rm -rf "$INSTALLDIR/temp"
    echo "$1"
    exit 1
}

if ! [ -f "$INSTALLDIR/disc1/fe.viv" ] ; then
    abort_and_cleanup "Disc 1 is invalid. Missing \"fe.viv\", exiting."
fi

if ! [ -f "$INSTALLDIR/disc2/SAR.exe" ] ; then
    abort_and_cleanup "Disc 2 is invalid. Missing \"SAR.exe\", exiting."
fi

echo "Downloading Wine-TkG"
curl -o "$INSTALLDIR/temp/wine.tar.xz" -L https://github.com/Kron4ek/Wine-Builds/releases/download/11.11/wine-11.11-staging-tkg-amd64-wow64.tar.xz
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to download Wine-TkG"
fi
echo "Extracting Wine-TkG"
tar -xf "$INSTALLDIR/temp/wine.tar.xz" -C "$INSTALLDIR"

echo "Downloading dxvk"
curl -o "$INSTALLDIR/temp/dxvk.tar.gz" -L https://github.com/doitsujin/dxvk/releases/download/v2.7.1/dxvk-2.7.1.tar.gz
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to download dxvk"
fi
mkdir "$INSTALLDIR/dxvk"
echo "Extracting dxvk"
tar -xf "$INSTALLDIR/temp/dxvk.tar.gz" -C "$INSTALLDIR/dxvk"

WINEDIR="$INSTALLDIR/wine-11.11-staging-tkg-amd64-wow64/bin"

echo "Initializing Wine prefix"

# Hacky way of fixing issues with SteamOS and its locked down package system :(
PRETTY_NAME=$(grep "PRETTY_NAME" /etc/os-release | cut -d'=' -f2 | tr -d '"')
if [[ $PRETTY_NAME == *"SteamOS" ]]; then
    echo "Steam OS detected, applying workarounds"
    export LD_LIBRARY_PATH="$("$HOME/.steam/root/ubuntu12_32/steam-runtime/run.sh" --print-steam-runtime-library-paths)"
    echo "Steam OS workarounds applied"
fi

WINEPREFIX="$INSTALLDIR/prefix" WINEDLLOVERRIDES=mscoree=d "$WINEDIR/wineboot" -i
echo "Wineboot"

WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wine" reg add "HKEY_LOCAL_MACHINE\\Software\\Wine\\Drives" /v t: /t REG_SZ /d cdrom
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to update registry, exiting."
fi

WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wine" reg add "HKEY_LOCAL_MACHINE\\Software\\Wine\\Drives" /v u: /t REG_SZ /d cdrom
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to update registry, exiting."
fi

WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wine" reg add "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v d3d8 /t REG_SZ /d native,builtin
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to update registry, exiting."
fi

WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wine" reg add "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v d3d9 /t REG_SZ /d native,builtin
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to update registry, exiting."
fi



WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wine" reg add "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v mscoree /t REG_SZ /d disabled
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to update registry, exiting."
fi

ln -s "$INSTALLDIR/disc1" "$INSTALLDIR/prefix/dosdevices/t:"
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to create disc1 symlink"
fi
ln -s "$INSTALLDIR/disc2" "$INSTALLDIR/prefix/dosdevices/u:"
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to create disc2 symlink."
fi
WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wineserver" -k # Apply the drive changes
WINEPREFIX="$INSTALLDIR/prefix" "$WINEDIR/wineboot"
echo "Applied registry"

# Remove the symlinks
WINE_USER=$(whoami)
rm "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Desktop"
rm "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Documents"
rm "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Downloads"
rm "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Music"
rm "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Pictures"
rm "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Videos"

# Recreate the folders
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Desktop"
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Documents"
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to create Wine doscuments dir"
fi
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Downloads"
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Music"
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Pictures"
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Videos"

mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Documents/NHL 2004"
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to create NHL 2004 Documents dir"
fi
mkdir "$INSTALLDIR/prefix/drive_c/users/$WINE_USER/Documents/NHL 2004/db"
if [ $? -ne 0 ] ; then
    abort_and_cleanup "Failed to create NHL 2004 Documents db dir"
fi

cd "$INSTALLDIR/disc1"
echo "Starting installer"
WINEPREFIX="$INSTALLDIR/prefix" WINEDLLOVERRIDES="winemenubuilder.exe=d" "$WINEDIR/wine" AutoRun.exe